// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAucUQsPSDErIhmQ6jVwtiqojIhqVi1Uus',
    appId: '1:529505025227:web:af8f21d442b6f3d563ef4e',
    messagingSenderId: '529505025227',
    projectId: 'logistics-now-306cb',
    authDomain: 'logistics-now-306cb.firebaseapp.com',
    databaseURL: 'https://logistics-now-306cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'logistics-now-306cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoQ8FnWNmGjpdm40Tcg5faerBLURqn0yk',
    appId: '1:529505025227:android:8875648fd91abba163ef4e',
    messagingSenderId: '529505025227',
    projectId: 'logistics-now-306cb',
    databaseURL: 'https://logistics-now-306cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'logistics-now-306cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL_OFLhgrW4Aa2V4Y6pIVb64iDo56ktEY',
    appId: '1:529505025227:ios:77f122dec17bc67a63ef4e',
    messagingSenderId: '529505025227',
    projectId: 'logistics-now-306cb',
    databaseURL: 'https://logistics-now-306cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'logistics-now-306cb.appspot.com',
    iosBundleId: 'com.example.logisticsnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL_OFLhgrW4Aa2V4Y6pIVb64iDo56ktEY',
    appId: '1:529505025227:ios:938d376f4855e40763ef4e',
    messagingSenderId: '529505025227',
    projectId: 'logistics-now-306cb',
    databaseURL: 'https://logistics-now-306cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'logistics-now-306cb.appspot.com',
    iosBundleId: 'com.example.logisticsnow.RunnerTests',
  );
}
